
services:
  kafka-1:
    image: bitnamilegacy/kafka:3.5.0
    ports:
      - "9191:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=qNqdb_SkTkGWwxFAUTOpXg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9095,3@kafka-3:9097
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9094,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://127.0.0.1:9191
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAMES=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /tmp/kafka-1:/bitnami/kafka/config
  kafka-2:
    image: bitnamilegacy/kafka:3.5.0
    ports:
      - "9192:9095"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_KRAFT_CLUSTER_ID=qNqdb_SkTkGWwxFAUTOpXg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9095,3@kafka-3:9097
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9095,CONTROLLER://:9094,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9095,EXTERNAL://127.0.0.1:9192
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAMES=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /tmp/kafka-1:/bitnami/kafka/config
  kafka-3:
    image: bitnamilegacy/kafka:3.5.0
    ports:
      - "9193:9097"
    environment:
      - KAFKA_CFG_NODE_ID=3
      - KAFKA_KRAFT_CLUSTER_ID=qNqdb_SkTkGWwxFAUTOpXg
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9092,2@kafka-2:9095,3@kafka-3:9097
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9097,CONTROLLER://:9094,EXTERNAL://:9098
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9097,EXTERNAL://127.0.0.1:9193
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAMES=PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /tmp/kafka-1:/bitnami/kafka/config